apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
spec:
  selector:
    matchLabels:
      app: pg-db
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      containers:
      - name: pg-db
        image: postgres:14.5
        env:
          - name: POSTGRES_PASSWORD
            value: "mypass"
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  type: ClusterIP
  selector:
    app: pg-db
  ports:
  - port: 5432
    targetPort: 5432