apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    name: mi-label-2
spec:
  containers:
  - name: test-app
    image: docker.io/nginx:1.23
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
  